name: StatsUpgrader
version: '${project.version}'
main: org.mrmelon__.statsupgrader.Main
api-version: '1.20'
commands:
  stats:
    aliases: st
    usage: "ยง4This player is not defined"
  adminsu:
    aliases: asu
    usage: "ยง4This argument is not defined, check TabCompleter"